let DATA={};let cat='masculino';
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function initials(n){return (n||'SM').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function fmtDate(d){if(!d)return 'Fecha por definir';const [y,m,day]=d.split('-');return `${day}/${m}/${y}`}
function getData(){return DATA[cat]}
function render(){const d=getData();const played=d.results.filter(x=>x.status==='Jugado').length;const pending=d.results.filter(x=>x.status!=='Jugado').length;const goals=d.results.reduce((s,x)=>s+(Number.isFinite(x.homeGoals)?x.homeGoals:0)+(Number.isFinite(x.awayGoals)?x.awayGoals:0),0);$('#played').textContent=played;$('#pending').textContent=pending;$('#goals').textContent=goals;$('#statusPill').textContent=played?'EN MARCHA':'PRÓXIMAMENTE';
 const upcoming=d.schedule.filter(x=>x.date&&x.home&&x.away&&x.score==='-'); const next=upcoming[0]; $('#nextRound').textContent=next?`Jornada ${next.round}`:''; $('#nextMatch').innerHTML=next?matchHTML(next):'<p class="meta">No hay partidos próximos cargados.</p>';
 const latest=d.results.filter(x=>x.status==='Jugado').slice(-4).reverse(); $('#latest').innerHTML=latest.length?latest.map(x=>`<div class="result-row"><span>${x.home}</span><span class="result-score">${x.homeGoals} - ${x.awayGoals}</span><span class="away">${x.away}</span></div>`).join(''):'<p class="meta">Aún no hay resultados registrados.</p>';
 const sorted=[...d.standings].filter(x=>x.pj>0||d.results.every(r=>r.status!=='Jugado')).sort((a,b)=>(b.pts-a.pts)||(b.dg-a.dg)||(b.gf-a.gf)||a.code-b.code); $('#miniTable').innerHTML=sorted.map((x,i)=>`<div class="result-row" style="grid-template-columns:32px 1fr 40px"><b>${x.pos||'—'}</b><span>${x.team}</span><b>${x.pts}</b></div>`).join('');
 renderSchedule();renderStandings();renderTeams();renderPlayers();}
function matchHTML(x){return `<div class="match"><div class="team"><div class="badge">${initials(x.home)}</div>${x.home||'Por definir'}</div><div><div class="score">${x.score&&x.score!=='-'?x.score:'VS'}</div><div class="vs">${fmtDate(x.date)}${x.time?' · '+x.time:''}</div></div><div class="team"><div class="badge">${initials(x.away)}</div>${x.away||'Por definir'}</div></div><div class="meta">${x.venue||'Cancha por definir'}${x.note?' · '+x.note:''}</div>`}
function renderSchedule(){const d=getData();const f=$('#roundFilter');f.innerHTML='<option value="all">Todas las jornadas</option>'+[...new Set(d.schedule.map(x=>x.round))].map(r=>`<option value="${r}">Jornada ${r}</option>`).join('');const filter=f.value||'all';const rows=d.schedule.filter(x=>filter==='all'||String(x.round)===filter);$('#scheduleTable').innerHTML=rows.map(x=>`<tr><td>${x.round}</td><td>#${x.match}</td><td>${fmtDate(x.date)}</td><td>${x.home||'Por definir'}</td><td><b>${x.score||'-'}</b></td><td>${x.away||'Por definir'}</td><td>${x.venue||'Por definir'}</td><td><span class="status ${x.score&&x.score!=='-'?'played':'pending'}">${x.score&&x.score!=='-'?'JUGADO':'PENDIENTE'}</span></td></tr>`).join('')}
function renderStandings(){const d=getData();const rows=[...d.standings].sort((a,b)=>{if(a.pj===0&&b.pj>0)return 1;if(a.pj>0&&b.pj===0)return -1;return (a.pos||99)-(b.pos||99)});$('#standingsTable').innerHTML=rows.map(x=>`<tr><td><b>${x.pos||'—'}</b></td><td><b>${x.team}</b></td><td>${x.pj}</td><td>${x.pg}</td><td>${x.pe}</td><td>${x.pp}</td><td>${x.gf}</td><td>${x.gc}</td><td>${x.dg}</td><td><b>${x.pts}</b></td><td>${x.pct?Math.round(x.pct*100)+'%':'0%'}</td></tr>`).join('')}
function renderTeams(){const d=getData();$('#teamGrid').innerHTML=d.teams.map(t=>{const s=d.standings.find(x=>x.code===t.code)||{};const players=d.players.filter(p=>p.team===t.name);return `<article class="team-card"><div class="team-logo">${initials(t.name)}</div><h3>${t.name}</h3><p>Código ${t.code} · ${players.length} jugadores</p><div class="team-stat"><span>PJ <b>${s.pj||0}</b></span><span>PTS <b>${s.pts||0}</b></span><span>DG <b>${s.dg||0}</b></span></div></article>`}).join('')}
function renderPlayers(){const d=getData();const f=$('#teamFilter');const current=f.value||'all';f.innerHTML='<option value="all">Todos los equipos</option>'+d.teams.map(t=>`<option>${t.name}</option>`).join('');f.value=current;const ps=d.players.filter(p=>current==='all'||p.team===current);$('#playerGrid').innerHTML=ps.length?ps.map(p=>`<div class="player"><div class="number">${p.number??'—'}</div><div><b>${p.name}</b><small>${p.team}</small><small>${p.role||'Jugador'}</small></div></div>`).join(''):'<p class="meta">No hay jugadores cargados para este filtro.</p>'}
$$('.navbtn').forEach(b=>b.onclick=()=>{ $$('.navbtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.section').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.section).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})});
$$('.cat').forEach(b=>b.onclick=()=>{$$('.cat').forEach(x=>x.classList.remove('active'));b.classList.add('active');cat=b.dataset.cat;render()});
$('#roundFilter').onchange=renderSchedule;$('#teamFilter').onchange=renderPlayers;$$('[data-go]').forEach(b=>b.onclick=()=>{const n=b.dataset.go;$$('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.section===n));$$('.section').forEach(x=>x.classList.toggle('active',x.id===n));window.scrollTo({top:0,behavior:'smooth'})});
fetch('data.json').then(r=>r.json()).then(x=>{DATA=x;render()});
